fix: properly import constants
Fixes attribute error in write_ledger_file:
```
  File "/Users/lukas/.virtualenvs/macx/lib/python3.12/site-packages/pyledger/text_ledger.py", line 198, in write_ledger_file
    missing = set(cls.REQUIRED_LEDGER_COLUMNS) - set(df.columns)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'TextLedger' has no attribute 'REQUIRED_LEDGER_COLUMNS'
```